### ISSUE TITLE
download Satellite AOD data

### ISSUE THREAD

**Issue by rhbertoldi** [ML-final-project/predicting_pm2.5#3]
I am having a hard time figuring out how to download this data - so I'm issuing this to you. 
[data source](https://neo.sci.gsfc.nasa.gov/view.php?datasetId=MYDAL2_M_AER_OD)

**Comment by akhil-ghanta** [comment]
Downloading this stuff is slightly more annoying than I thought it would be. I'm gonna ask Adrien about this one.
