### ISSUE TITLE
justify 15 km

### ISSUE THREAD

**Issue by rhbertoldi** [ML-final-project/predicting_pm2.5#9]
~continuation of #4~

~Buffered pm2.5 monitoring sites by 15km.~
~- [ ] validate 15km~
~Chicago midway, la grande on December - identical pm2.5 : 16.35714~
~- [ ] get correlation between monitoring sites within Chicago~
~- [ ] validate buffering pm25 over noaa~
~- [ ] generate estimates at 10 and 15 km~

**Comment by gillsarah** [comment]
The standards for the measurements are set by the World Meteorological Organization. 
https://www.wmo.int/pages/prog/www/IMOP/meetings/CB/Ed-Board-2/EdBd-2_P-I_Ch-1.doc 

-this might indicate 3km for air pollution :(

**Comment by gillsarah** [comment]
15km:
Paper modeling pm25 in LA uses 100m and 200m buffers
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5841919/

**Comment by rhbertoldi** [comment]
> 
> 
> The standards for the measurements are set by the World Meteorological Organization.
> https://www.wmo.int/pages/prog/www/IMOP/meetings/CB/Ed-Board-2/EdBd-2_P-I_Ch-1.doc
> 
> -this might indicate 3km for air pollution :(

@gillsarah
That's a bummer. There is only one NOAA monitoring site that is within 3km of a pm2.5 monitoring site. 
I'm assuming you're grabbing this from the quote - "resolution of phenomena...toposcale or local scale (100–3 km), for example, air pollution, tornadoes".

**Comment by gillsarah** [comment]
Yes. Though that doc is less helpful than I thought when I commented this

**Comment by rhbertoldi** [comment]
![3o6mvv](https://user-images.githubusercontent.com/49281577/73792468-fec9d600-4769-11ea-8608-6f11184fec85.gif)

**Comment by rhbertoldi** [comment]
NOT BUFFERING ANYMORE - just using closest distances. closing ticket.
